# Generated by Django 4.1.7 on 2023-12-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('work_in', models.CharField(choices=[('D', 'Director'), ('M', 'Maintenance'), ('S', 'Security'), ('MK', 'Marketing'), ('I', 'Investigador'), ('DV', 'Developer'), ('SL', 'Seller'), ('NT', 'Not Asigned')], default='NT', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Employee',
            },
        ),
    ]
